# standard jekyll configuration

name: Jackarain
url: http://jack.p2sp.net
description: Jack's blog

permalink: date
pygments: true
markdown: rdiscount
baseurl: /

source: .
#destination: ./_site
#plugins: ./_plugins

# configuration required for some pages

domain: jack.p2sp.net
title: Jack's blog
author: Jack
email: jack.wgm@gmail.com

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

github:
   username: Jackarain

disqus:
   id: jack
